# Generated by Django 5.2.8 on 2025-11-06 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TicketModel",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("status", models.CharField(default="OPEN", max_length=20)),
                ("category", models.CharField(blank=True, max_length=20, null=True)),
                ("priority", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tickets",
                "ordering": ["-created_at"],
            },
        ),
    ]
